### ISSUE TITLE
Product filtering improvements.

### ISSUE THREAD

**Issue by Trost123** [webasyst/dummy-theme#4] opened 2017-01-28 15:04 UTC
1) AJAX filters replace a DIV that contains entire page at the moment. I think it would be enough just to replace the product grid? (Like in Default 3.0)

2) AJAX filters only apply when you click on the button. Why not make it work like in Default 3.0, where it updates immediately when user changes a filter?

3) We could add this to make filter changes appear in tab history (back button in browser).
```
// Filter history
if (!!(history.pushState && history.state !== undefined)) {
window.history.pushState({}, '', '?'+data+'&filter');
}
```

**Comment by Leonix** [comment] 2017-11-02 10:44
2. Filters not applying on change is by design in this theme. Should not be difficult to modify this behaviour, though.

Rest should be fixed in shop/dummy 1.0.6.

**Closed as completed by Leonix** 2017-11-02 10:44 UTC
